### ISSUE TITLE
update plugin

### ISSUE THREAD

**Issue by petroulias** [Antreasgr/AlphaBankGatewayWooCommerce#10]
Hi
Για το Redirection model, θα πρέπει πλέον υποχρεωτικά να στέλνετε τις μεταβλητές, billCountry, billState, billZip, billCity και billAddress με το αίτημά σας προς την πλατφόρμα.

For the Redirection model, you will now be required to send variables, billCountry, billState, billZip, billCity and billAddress with your request to the platform.

How we can resolve this?
Thanks

**Comment by inter-shop** [comment]
hello 
πως θα μπορουσα να κανω το plugin   ( compliant with new EMV 3D Secure specifications)  eyxaristw VASILIS APO LARISA
