### ISSUE TITLE
Masterpass option in payment method

### ISSUE THREAD

**Issue by tsynodinos** [Antreasgr/AlphaBankGatewayWooCommerce#7]
The bank requires another payment option in the checkout page, Masterpass, and the variable payMethod has changed. If it is empty the client will pay using a credit card or if it has the attr "auto:MasterPass" the client will pay using the Masterpass wallet.

Any ideas?

**Comment by NikosTsolakos** [comment]
I have the same problem!
it’s a var only “auto:MasterPass” but it’s complicated

**Comment by shoorty01** [comment]
Same problem here. Does anyone knows if this will be included soon?
Thank you
